steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'node-app',
      '--image', 'gcr.io/$PROJECT_ID/node-app:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

timeout: '600s'