steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/momenai/cloud-run-source-deploy/momenai/next-app-image",
        "."
      ]
options:
  logging: CLOUD_LOGGING_ONLY
