steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-docker.pkg.dev/momenai/cloud-run-source-deploy/momenai/next-app-image",
        ".",
      ]
  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-docker.pkg.dev/momenai/cloud-run-source-deploy/momenai/next-app-image",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
