steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/next-app-container-repo/next-app-image",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/next-app-container-repo/next-app-image",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
